name: monday
description: Unofficial Monday API Wrapper
version: 1.1.1
repository: https://github.com/ArcaneArts/monday
environment:
  sdk: ^3.5.2
dependencies:
  dart_mappable: ^4.3.0
  http: ^1.2.2
  toxic: ^1.3.2
dev_dependencies:
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.3.0
